"""Add menu item and link recipes to menu

Revision ID: e7e2b33a5b55
Revises: 522453224570
Create Date: 2025-04-09 14:46:37.956980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e2b33a5b55'
down_revision = '522453224570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('recipe_item_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'menu_item', ['menu_item_id'], ['id'])
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('recipe_item_name_key', ['item_name'])
        batch_op.drop_column('menu_item_id')

    op.drop_table('menu_item')
    # ### end Alembic commands ###
